name: products_store
description: "Ecommerce app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_functions: ^6.0.1

  #state management
  flutter_bloc: ^9.1.1

  #ui
  awesome_snackbar_content: ^0.1.6

  #other
  equatable: ^2.0.7



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

