name: products_store
description: "Ecommerce app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  #ios
  cupertino_icons: ^1.0.8

  #firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_functions: ^6.0.1
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2

  #local storage
  shared_preferences: ^2.5.3

  #network
  http: ^1.5.0

  #state management
  flutter_bloc: ^9.1.1

  #ui
  awesome_snackbar_content: ^0.1.6
  cached_network_image: ^3.4.1
  badges: ^3.1.2

  #navigation
  go_router: ^16.2.1

  #other
  equatable: ^2.0.7
  uuid: ^4.5.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.5



dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.8.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:

  uses-material-design: true

